name: InfernalMobsReloaded
main: jacob_vejvoda.infernal_mobs.infernal_mobs
version: 1.0
softdepend: [Vault]
api-version: 1.21
authors: [Eliminator]
contributors: [Kre0lidge]
description: Add Infernal Mobs with special abilities to your server!

commands:
  infernalmobs:
    aliases: [im]
    description: "Base command for Infernal Mobs."
    usage: /<command>
    permission: infernal.commands
    permission-message: "You do not have permission to use this command"