name: InfernalMobsReloaded
main: jacob_vejvoda.infernal_mobs.InfernalMobs
version: 1.0
api-version: 1.21.7
authors: [Eliminator, Kre0lidge]
description: Add Infernal Mobs with special abilities to your server!

commands:
  infernalmobs:
    aliases: [im]
    description: "Base command for Infernal Mobs."
    usage: /<command>
    permission: infernal.commands
    permission-message: "You do not have permission to use this command"